services:
  - type: web
    name: seranjivi-crm-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 server.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
    pythonVersion: 3.10
